-- AlterTable
ALTER TABLE `Memo` ADD COLUMN `date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `Student` ADD COLUMN `classDays` VARCHAR(191) NULL,
    ADD COLUMN `classTime` VARCHAR(191) NULL;
